apiVersion: v1
kind: Pod
metadata:
  name: coronapod
  labels:
    version: "1.0"
spec:
  containers:
    - name: corona
      image: techsriman/corona:1.0
      ports:
        - name: tomcatport
          containerPort: 8081
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8081
        initialDelaySeconds: 10
        timeoutSeconds: 10
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8081
        initialDelaySeconds: 10
        timeoutSeconds: 10
        failureThreshold: 3
      resources:
        requests:
          cpu: 1
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1024Mi
      env:
        - name: guidelines.oxygenLevels
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap
              key: oxygenLevels
        - name: guidelines.quarantine
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap              
              key: quarantine
        - name: guidelines.liters
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap              
              key: liters
        - name: guidelines.temparatureLevels
          valueFrom:
            configMapKeyRef:
              name: guidelinesconfigmap              
              key: temparatureLevels        

                  